include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - /**/*.g.dart
    - /**/assets.gen.dart

linter:
  rules: 
    avoid_print: true
    prefer_single_quotes: true

# TODO: decide to learn more about this file by that details - https://dart.dev/guides/language/analysis-options
# TODO: also check rules below, that was written by best practices (don't just uncomment, read more before):
# analyzer:
#   plugins:
#     - dart_code_metrics
#   exclude:
#     - /**/*.g.dart
#     - /**/injection.config.dart
#     - lib/core/di/injection.config.dart
#     - /**/assets.gen.dart

#   errors:
#     always_put_required_named_parameters_first: warning
#     always_use_package_imports: error
#     annotate_overrides: error
#     avoid_annotating_with_dynamic: info
#     avoid_bool_literals_in_conditional_expressions: error
#     avoid_positional_boolean_parameters: error
#     avoid_print: error
#     avoid_redundant_argument_values: error
#     avoid_returning_null: info
#     avoid_returning_null_for_void: error
#     avoid_unnecessary_containers: error
#     avoid_unused_constructor_parameters: error
#     avoid_void_async: error
#     await_only_futures: error
#     camel_case_types: error
#     cancel_subscriptions: error
#     cascade_invocations: error
#     control_flow_in_finally: error
#     dead_code: warning
#     empty_statements: error
#     file_names: error
#     join_return_with_assignment: warning
#     missing_required_param: error
#     missing_return: error
#     no_logic_in_create_state: error
#     no_runtimeType_toString: error
#     only_throw_errors: warning
#     prefer_asserts_in_initializer_lists: warning
#     prefer_constructors_over_static_methods: error
#     prefer_const_constructors: error
#     prefer_is_not_operator: error
#     prefer_null_aware_operators: error
#     prefer_void_to_null: error
#     sized_box_for_whitespace: error
#     sort_child_properties_last: warning
#     todo: info
#     unnecessary_await_in_return: error
#     unnecessary_brace_in_string_interps: error
#     unnecessary_lambdas: error
#     unnecessary_null_aware_assignments: error
#     unnecessary_overrides: error
#     unnecessary_parenthesis: error
#     unnecessary_raw_strings: error
#     unnecessary_string_interpolations: error
#     use_full_hex_values_for_flutter_colors: error
#     use_is_even_rather_than_modulo: error
#     use_key_in_widget_constructors: error
#     use_rethrow_when_possible: error
#     use_string_buffers: error
#     use_to_and_as_if_applicable: error

# linter:
#   rules:
#     no_leading_underscores_for_local_identifiers: false
#     always_put_required_named_parameters_first: true
#     always_use_package_imports: true
#     avoid_annotating_with_dynamic: true
#     avoid_bool_literals_in_conditional_expressions: true
#     avoid_positional_boolean_parameters: true
#     avoid_redundant_argument_values: true
#     avoid_returning_null: true
#     avoid_returning_null_for_void: true
#     avoid_unused_constructor_parameters: true
#     avoid_void_async: true
#     cancel_subscriptions: true
#     cascade_invocations: true
#     close_sinks: true
#     comment_references: true
#     control_flow_in_finally: true
#     join_return_with_assignment: true
#     leading_newlines_in_multiline_strings: true
#     missing_whitespace_between_adjacent_strings: true
#     no_runtimeType_toString: true
#     omit_local_variable_types: false
#     only_throw_errors: true
#     parameter_assignments: true
#     prefer_asserts_in_initializer_lists: true
#     prefer_constructors_over_static_methods: true
#     prefer_if_elements_to_conditional_expressions: true
#     prefer_interpolation_to_compose_strings: true
#     sort_child_properties_last: true
#     sort_pub_dependencies: true
#     sort_unnamed_constructors_first: true
#     unawaited_futures: false
#     unnecessary_await_in_return: true
#     unnecessary_lambdas: true
#     unnecessary_null_aware_assignments: true
#     unnecessary_parenthesis: true
#     use_is_even_rather_than_modulo: true
#     use_string_buffers: true
#     use_to_and_as_if_applicable: true
#     depend_on_referenced_packages: false