name: test_list_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
isar_version: &isar_version 3.1.0

# TODO: read information below
# environment:
#   sdk: ^3.5.4

# TODO: decide to use more flexible conditions for sdk version, like this:
# TODO: also use always the latest version of flutter and dart, execute then `flutter upgrade`
environment:
  sdk: '>=3.6.1 <4.0.0' # 3.6.1 is the latest version of dart, that is used in this project
  flutter: '>=3.27.3 <4.0.0' # 3.27.3 is the latest version of flutter, that is used in this project

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.1
  dio: ^5.7.0
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  talker_flutter: ^4.6.6
  talker_dio_logger: ^4.6.6
  talker_bloc_logger: ^4.6.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_messaging: ^15.2.1
  auto_route: ^9.3.0+1
  loading_animation_widget: ^1.3.0
  delayed_widget: ^1.1.2
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.8.0
  email_validator_flutter: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.3.0+1
  build_runner: ^2.4.14
  freezed: ^2.5.8
  # isar_generator: ^3.1.0+1 # <- TODO: issue with version solving failed (without that everything is working)

# Tried to fix it, but it sometimes work, sometimes not (in that case this not working)
# Iteratively try to dependency overrides (sometimes it helps)
# dependency_overrides:
#   source_gen: ^2.0.0
#   dart_style: ^3.0.1
#   analyzer: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/bitcoin-logo.png
    - assets/png/logo_test.png
    - assets/jpg/hand-holding-bitcoin-coin.jpg
    - assets/jpg/modern.jpg
    - assets/png/untitled1.png 
    - assets/png/ai-generated.png 