// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMjKmd-lpIxagBw0R9N3_LUiNIdXXlqD8',
    appId: '1:109701368635:web:fb09aa39a0471d52de051e',
    messagingSenderId: '109701368635',
    projectId: 'cryptocion-1298b',
    authDomain: 'cryptocion-1298b.firebaseapp.com',
    storageBucket: 'cryptocion-1298b.firebasestorage.app',
    measurementId: 'G-E7S29Y5TXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtk1tdmdTVaSyco1f48F5KHMpGRBE40wo',
    appId: '1:109701368635:android:77eaed9707cb488fde051e',
    messagingSenderId: '109701368635',
    projectId: 'cryptocion-1298b',
    storageBucket: 'cryptocion-1298b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPYdUtWFqiv0CjBFvoQ-MHoTw7s1JkBTE',
    appId: '1:109701368635:ios:1df50140d77bb2bdde051e',
    messagingSenderId: '109701368635',
    projectId: 'cryptocion-1298b',
    storageBucket: 'cryptocion-1298b.firebasestorage.app',
    iosBundleId: 'com.yatsunhanna.testListFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPYdUtWFqiv0CjBFvoQ-MHoTw7s1JkBTE',
    appId: '1:109701368635:ios:1df50140d77bb2bdde051e',
    messagingSenderId: '109701368635',
    projectId: 'cryptocion-1298b',
    storageBucket: 'cryptocion-1298b.firebasestorage.app',
    iosBundleId: 'com.yatsunhanna.testListFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMjKmd-lpIxagBw0R9N3_LUiNIdXXlqD8',
    appId: '1:109701368635:web:794f7c950eac2fd4de051e',
    messagingSenderId: '109701368635',
    projectId: 'cryptocion-1298b',
    authDomain: 'cryptocion-1298b.firebaseapp.com',
    storageBucket: 'cryptocion-1298b.firebasestorage.app',
    measurementId: 'G-ZX2S1T0DH6',
  );
}
